import type { INestApplication } from '@nestjs/common';
import type { PrismaClient, StaffRole } from '@repo/db';
import type { Server } from 'node:http';
import request from 'supertest';

import { createTestApp } from './app.js';
import {
  createTestPrismaClient,
  deleteTestRunData,
  testCode,
} from './database.js';
import { createTestOrganization, createTestStaff, signIn } from './staff.js';

/**
 * Business settings over HTTP (US-094): the statuses each role actually gets,
 * and the three refusals that carry the classification — immutable, locked by
 * history, and an invalid value. The route × role grid is generated by
 * `rbac-matrix.e2e-spec.ts`; the cells here are the ones a Super Admin's
 * screen depends on.
 *
 * Nothing here disburses, collects, closes a day or writes an append-only
 * table: audit entries are captured by `createTestApp`, the `setting` rows and
 * the one PENDING account belong to a run-tagged organisation, and
 * `deleteTestRunData` removes them.
 */
describe('business settings (US-094, e2e)', () => {
  let app: INestApplication<Server>;
  let prisma: PrismaClient;
  let organizationId: string;
  let lineId: string;
  let sectorId: string;
  const cookies: Record<string, string> = {};

  const as = (who: string) => ({
    get: (path: string) =>
      request(app.getHttpServer()).get(path).set('Cookie', cookies[who]!),
    patch: (path: string) =>
      request(app.getHttpServer()).patch(path).set('Cookie', cookies[who]!),
  });

  const setting = (body: { settings: { key: string }[] }, key: string) =>
    body.settings.find((each) => each.key === key) as Record<string, unknown>;

  beforeAll(async () => {
    prisma = createTestPrismaClient();
    app = await createTestApp();
    const org = await createTestOrganization(prisma, ['Line A']);
    organizationId = org.organization.id;
    sectorId = org.sector.id;
    lineId = org.lines[0]!.id;

    const roles: [string, StaffRole][] = [
      ['superAdmin', 'SUPER_ADMIN'],
      ['admin', 'ADMIN'],
      ['senior', 'SENIOR'],
      ['junior', 'JUNIOR'],
    ];
    for (const [who, role] of roles) {
      const staff = await createTestStaff(prisma, {
        organizationId,
        role,
        label: who,
      });
      if (role === 'SENIOR' || role === 'JUNIOR') {
        await prisma.lineAssignment.create({
          data: {
            staffProfileId: staff.staffProfileId,
            lineId,
            assignmentRole: role,
            effectiveFrom: new Date('2026-01-01'),
          },
        });
      }
      cookies[who] = await signIn(app, staff);
    }
  });

  afterAll(async () => {
    await app.close();
    await deleteTestRunData(prisma);
    await prisma.$disconnect();
  });

  describe('who may see and change them', () => {
    it('answers the Super Admin with every setting at its default', async () => {
      const response = await as('superAdmin').get('/api/settings').expect(200);

      expect(response.body.hasHistory).toBe(false);
      expect(setting(response.body, 'account.defaultTermDays')).toMatchObject({
        value: '100',
        group: 'FORWARD_ONLY',
        editable: true,
      });
      expect(setting(response.body, 'organisation.timezone')).toMatchObject({
        value: 'Asia/Kolkata',
        group: 'LOCKED',
        editable: false,
      });
    });

    it.each(['admin', 'senior', 'junior'])(
      'refuses %s the settings entirely',
      async (who) => {
        await as(who).get('/api/settings').expect(403);
        await as(who)
          .patch('/api/settings/account.defaultTermDays')
          .send({ value: '60' })
          .expect(403);
      },
    );

    it('refuses a caller with no session', async () => {
      await request(app.getHttpServer()).get('/api/settings').expect(401);
    });
  });

  describe('changing one', () => {
    it('moves the default term and carries it to whoever opens the account form', async () => {
      const changed = await as('superAdmin')
        .patch('/api/settings/account.defaultTermDays')
        .send({ value: '60' })
        .expect(200);
      expect(setting(changed.body, 'account.defaultTermDays')).toMatchObject({
        value: '60',
        isOverridden: true,
      });

      const me = await as('admin').get('/api/me').expect(200);
      expect(me.body.organization.defaultTermDays).toBe(60);

      const reset = await as('superAdmin')
        .patch('/api/settings/account.defaultTermDays')
        .send({ value: null })
        .expect(200);
      expect(setting(reset.body, 'account.defaultTermDays')).toMatchObject({
        value: '100',
        isOverridden: false,
      });
    });

    it('changes the business name, which restates nothing', async () => {
      const renamed = testCode('ORG');

      const response = await as('superAdmin')
        .patch('/api/settings/organisation.name')
        .send({ value: renamed })
        .expect(200);

      expect(setting(response.body, 'organisation.name')).toMatchObject({
        value: renamed,
      });
      const me = await as('superAdmin').get('/api/me').expect(200);
      expect(me.body.organization.name).toBe(renamed);
    });

    it('refuses a value outside the setting’s range, naming the field', async () => {
      const response = await as('superAdmin')
        .patch('/api/settings/account.overdueGraceDays')
        .send({ value: '400' })
        .expect(400);

      expect(response.body.code).toBe('SETTING_VALUE_INVALID');
      expect(response.body.details).toEqual([
        { field: 'value', issue: expect.stringContaining('whole number') },
      ]);
    });

    it('refuses the value already in force', async () => {
      const response = await as('superAdmin')
        .patch('/api/settings/account.overdueGraceDays')
        .send({ value: '0' })
        .expect(422);

      expect(response.body.code).toBe('SETTING_UNCHANGED');
    });

    it('answers an unknown key with 404, not 400', async () => {
      const response = await as('superAdmin')
        .patch('/api/settings/account.interestRate')
        .send({ value: '12' })
        .expect(404);

      expect(response.body.code).toBe('SETTING_NOT_FOUND');
    });

    it('refuses the time zone outright — it is settled in code (BR-12)', async () => {
      const response = await as('superAdmin')
        .patch('/api/settings/organisation.timezone')
        .send({ value: 'Asia/Dubai' })
        .expect(422);

      expect(response.body.code).toBe('SETTING_IMMUTABLE');
    });

    it('refuses the sign-in link, whatever the state of the business', async () => {
      const response = await as('superAdmin')
        .patch('/api/settings/organisation.slug')
        .send({ value: 'another-slug' })
        .expect(422);

      expect(response.body.code).toBe('SETTING_IMMUTABLE');
    });
  });

  describe('once the business has an account', () => {
    beforeAll(async () => {
      const customer = await prisma.customer.create({
        data: {
          organizationId,
          customerCode: testCode('CUS'),
          name: 'Settings Customer',
          mobile: '+919800000111',
          address: 'Address',
          sectorId,
          lineId,
        },
      });
      // PENDING: never disbursed, so it has no ledger rows and cleanup removes it.
      await prisma.accountLoan.create({
        data: {
          organizationId,
          accountCode: testCode('ACC'),
          customerId: customer.id,
          lineId,
          accountAmount: '1000',
          investedAmount: '900',
          profitAmount: '100',
          dailyAmount: '100',
          termDays: 10,
          outstandingAmount: '1000',
          status: 'PENDING',
          disbursementDate: new Date('2026-01-03'),
          firstCollectionDate: new Date('2026-01-05'),
          targetCompletionDate: new Date('2026-01-16'),
        },
      });
    });

    it('locks the currency, because every posted amount is in it', async () => {
      const response = await as('superAdmin')
        .patch('/api/settings/organisation.currency')
        .send({ value: 'AED' })
        .expect(422);

      expect(response.body.code).toBe('SETTING_LOCKED_BY_HISTORY');
      const listed = await as('superAdmin').get('/api/settings').expect(200);
      expect(listed.body.hasHistory).toBe(true);
      expect(setting(listed.body, 'organisation.currency')).toMatchObject({
        value: 'INR',
        editable: false,
      });
    });

    it('still lets the forward-only and free settings move', async () => {
      const response = await as('superAdmin')
        .patch('/api/settings/account.overdueGraceDays')
        .send({ value: '2' })
        .expect(200);

      expect(setting(response.body, 'account.overdueGraceDays')).toMatchObject({
        value: '2',
        editable: true,
      });
    });
  });
});
