import type { INestApplication } from '@nestjs/common';
import type { PrismaClient, StaffRole } from '@repo/db';
import { randomInt } from 'node:crypto';
import type { Server } from 'node:http';
import request from 'supertest';

import { createTestApp } from './app.js';
import {
  createTestPrismaClient,
  deleteTestRunData,
  testEmail,
} from './database.js';
import {
  createTestOrganization,
  createTestStaff,
  signIn,
  type TestStaff,
} from './staff.js';

/**
 * Staff administration over HTTP (US-092): the statuses each role actually
 * gets, and the safety rules of the matrix's *row* half — no escalation, never
 * on yourself, never on someone senior, and never a silent loss of an open
 * assignment. The action half (route × role) is generated by
 * `rbac-matrix.e2e-spec.ts`.
 *
 * Nothing here disburses, collects, closes a day or writes an append-only
 * table: audit entries are captured by `createTestApp`, and every user this
 * suite creates carries the run tag so `deleteTestRunData` removes it.
 */
describe('staff administration (US-092, e2e)', () => {
  let app: INestApplication<Server>;
  let prisma: PrismaClient;
  let organizationId: string;
  let lineId: string;
  const cookies: Record<string, string> = {};
  const staff: Record<string, TestStaff> = {};

  const as = (who: string) => ({
    post: (path: string) =>
      request(app.getHttpServer()).post(path).set('Cookie', cookies[who]!),
    patch: (path: string) =>
      request(app.getHttpServer()).patch(path).set('Cookie', cookies[who]!),
    get: (path: string) =>
      request(app.getHttpServer()).get(path).set('Cookie', cookies[who]!),
    delete: (path: string) =>
      request(app.getHttpServer()).delete(path).set('Cookie', cookies[who]!),
  });

  const newStaff = (overrides: Record<string, unknown> = {}) => ({
    name: 'Meena Collector',
    email: testEmail('created'),
    phone: `+919${randomInt(100_000_000, 999_999_999)}`,
    role: 'JUNIOR',
    ...overrides,
  });

  /** A person this suite may change without disturbing the signed-in actors. */
  async function subject(role: StaffRole = 'JUNIOR') {
    return createTestStaff(prisma, {
      organizationId,
      role,
      label: 'subject',
    });
  }

  beforeAll(async () => {
    prisma = createTestPrismaClient();
    app = await createTestApp();
    const org = await createTestOrganization(prisma, ['Line A']);
    organizationId = org.organization.id;
    lineId = org.lines[0]!.id;

    const roles: [string, StaffRole][] = [
      ['superAdmin', 'SUPER_ADMIN'],
      ['admin', 'ADMIN'],
      ['senior', 'SENIOR'],
      ['junior', 'JUNIOR'],
    ];
    for (const [who, role] of roles) {
      staff[who] = await createTestStaff(prisma, {
        organizationId,
        role,
        label: who,
      });
      cookies[who] = await signIn(app, staff[who]!);
    }
    // The Senior needs a line to be in scope at all (M02).
    await prisma.lineAssignment.create({
      data: {
        staffProfileId: staff.senior!.staffProfileId,
        lineId,
        assignmentRole: 'SENIOR',
        effectiveFrom: new Date('2026-01-01'),
      },
    });

    const elsewhere = await createTestOrganization(prisma);
    staff.outsider = await createTestStaff(prisma, {
      organizationId: elsewhere.organization.id,
      role: 'JUNIOR',
      label: 'outsider',
    });
  });

  afterAll(async () => {
    await app.close();
    await deleteTestRunData(prisma);
    await prisma.$disconnect();
  });

  describe('POST /api/staff', () => {
    it('an Admin creates a staff member and is given the temporary password once', async () => {
      const body = newStaff();
      const response = await as('admin')
        .post('/api/staff')
        .send(body)
        .expect(201);

      expect(response.body.staff).toMatchObject({
        name: body.name,
        email: body.email,
        phone: body.phone,
        role: 'JUNIOR',
        status: 'ACTIVE',
        currentAssignment: null,
      });
      expect(response.body.temporaryPassword).toHaveLength(12);

      // The new person is in the Team list straight away, and must change
      // their password before anything else (US-003's flow, not a new one).
      const listed = await as('admin').get('/api/staff?limit=200').expect(200);
      expect(
        listed.body.data.map(
          (row: { staffProfileId: string }) => row.staffProfileId,
        ),
      ).toContain(response.body.staff.staffProfileId);

      const created = await signIn(app, {
        email: body.email,
        password: response.body.temporaryPassword,
      });
      const blocked = await request(app.getHttpServer())
        .get('/api/me')
        .set('Cookie', created)
        .expect(403);
      expect(blocked.body.code).toBe('PASSWORD_CHANGE_REQUIRED');
    });

    it('a Senior and a Junior are refused (403), as the matrix says', async () => {
      for (const who of ['senior', 'junior']) {
        const response = await as(who)
          .post('/api/staff')
          .send(newStaff())
          .expect(403);
        expect(response.body.code).toBe('PERMISSION_DENIED');
      }
    });

    it('an Admin cannot create a Super Admin (403), but a Super Admin can', async () => {
      const refused = await as('admin')
        .post('/api/staff')
        .send(newStaff({ role: 'SUPER_ADMIN' }))
        .expect(403);
      expect(refused.body.code).toBe('ROLE_ABOVE_OWN');

      await as('superAdmin')
        .post('/api/staff')
        .send(newStaff({ role: 'SUPER_ADMIN' }))
        .expect(201);
    });

    it('refuses a duplicate email or mobile (409) and a malformed body (400)', async () => {
      const body = newStaff();
      await as('admin').post('/api/staff').send(body).expect(201);

      const email = await as('admin')
        .post('/api/staff')
        .send(newStaff({ email: body.email }))
        .expect(409);
      expect(email.body.code).toBe('EMAIL_TAKEN');

      const phone = await as('admin')
        .post('/api/staff')
        .send(newStaff({ phone: body.phone }))
        .expect(409);
      expect(phone.body.code).toBe('PHONE_TAKEN');

      await as('admin')
        .post('/api/staff')
        .send(newStaff({ phone: '12345' }))
        .expect(400);
      await as('admin')
        .post('/api/staff')
        .send(newStaff({ role: 'OWNER' }))
        .expect(400);
    });
  });

  describe('PATCH /api/staff/:staffProfileId', () => {
    it('an Admin corrects a name and mobile number', async () => {
      const person = await subject();
      const phone = `+919${randomInt(100_000_000, 999_999_999)}`;

      const response = await as('admin')
        .patch(`/api/staff/${person.staffProfileId}`)
        .send({ name: 'Corrected Name', phone })
        .expect(200);

      expect(response.body).toMatchObject({ name: 'Corrected Name', phone });
    });

    it('a Senior is refused (403); another organisation’s staff is 404', async () => {
      const person = await subject();
      await as('senior')
        .patch(`/api/staff/${person.staffProfileId}`)
        .send({ name: 'No', phone: '+919800000001' })
        .expect(403);

      const missing = await as('admin')
        .patch('/api/staff/does-not-exist')
        .send({ name: 'No', phone: '+919800000002' })
        .expect(404);
      const outsider = await as('admin')
        .patch(`/api/staff/${staff.outsider!.staffProfileId}`)
        .send({ name: 'No', phone: '+919800000003' })
        .expect(404);
      expect(outsider.body.code).toBe(missing.body.code);
      expect(outsider.body.message).toBe(missing.body.message);
    });
  });

  describe('POST /api/staff/:staffProfileId/role', () => {
    it('only a Super Admin may change a role — an Admin is 403', async () => {
      const person = await subject();
      const refused = await as('admin')
        .post(`/api/staff/${person.staffProfileId}/role`)
        .send({ role: 'SENIOR' })
        .expect(403);
      expect(refused.body.code).toBe('PERMISSION_DENIED');

      const changed = await as('superAdmin')
        .post(`/api/staff/${person.staffProfileId}/role`)
        .send({ role: 'SENIOR' })
        .expect(200);
      expect(changed.body.role).toBe('SENIOR');
    });

    it('refuses the Super Admin’s own role (422), whatever they send', async () => {
      const response = await as('superAdmin')
        .post(`/api/staff/${staff.superAdmin!.staffProfileId}/role`)
        .send({ role: 'JUNIOR' })
        .expect(422);
      expect(response.body.code).toBe('CANNOT_CHANGE_OWN_ROLE');

      const me = await as('superAdmin').get('/api/me').expect(200);
      expect(me.body.role).toBe('SUPER_ADMIN');
    });

    it('is 404 for another organisation’s staff, worded as for a missing one', async () => {
      // The most senior route, so prove it too: out of scope reads as missing,
      // never as forbidden, or the refusal itself confirms the person exists.
      const missing = await as('superAdmin')
        .post('/api/staff/does-not-exist/role')
        .send({ role: 'SENIOR' })
        .expect(404);
      const outsider = await as('superAdmin')
        .post(`/api/staff/${staff.outsider!.staffProfileId}/role`)
        .send({ role: 'SENIOR' })
        .expect(404);
      expect(outsider.body.code).toBe(missing.body.code);
      expect(outsider.body.message).toBe(missing.body.message);
    });

    it('refuses while an open line assignment contradicts the new role (422)', async () => {
      const response = await as('superAdmin')
        .post(`/api/staff/${staff.senior!.staffProfileId}/role`)
        .send({ role: 'ADMIN' })
        .expect(422);
      expect(response.body.code).toBe('STAFF_HAS_OPEN_ASSIGNMENT');
      expect(response.body.details).toEqual([
        expect.objectContaining({ field: 'role' }),
      ]);
    });
  });

  describe('DELETE /api/staff/:staffProfileId', () => {
    it('a Super Admin deletes someone who has left: gone from the list, signed out, record kept', async () => {
      const person = await subject();

      const removed = await as('superAdmin')
        .delete(`/api/staff/${person.staffProfileId}`)
        .expect(200);
      expect(removed.body).toMatchObject({
        staffProfileId: person.staffProfileId,
        sessionsRevoked: expect.any(Number),
      });
      expect(removed.body.deletedAt).toEqual(expect.any(String));

      // Gone from the directory, and a second delete cannot find them.
      const listed = await as('superAdmin')
        .get('/api/staff?limit=200')
        .expect(200);
      expect(
        listed.body.data.map(
          (row: { staffProfileId: string }) => row.staffProfileId,
        ),
      ).not.toContain(person.staffProfileId);
      await as('superAdmin')
        .delete(`/api/staff/${person.staffProfileId}`)
        .expect(404);
      // The row itself stays: history keeps its actor.
      expect(
        await prisma.staffProfile.findUnique({
          where: { id: person.staffProfileId },
        }),
      ).not.toBeNull();
    });

    it('an Admin may delete too (decided 2026-09-20); a Senior or Junior may not', async () => {
      const person = await subject();
      for (const who of ['senior', 'junior']) {
        const refused = await as(who)
          .delete(`/api/staff/${person.staffProfileId}`)
          .expect(403);
        expect(refused.body.code).toBe('PERMISSION_DENIED');
      }
      expect(
        (
          await prisma.staffProfile.findUniqueOrThrow({
            where: { id: person.staffProfileId },
          })
        ).deletedAt,
      ).toBeNull();

      // An Admin may remove someone who has left — but never the owner.
      const other = await subject();
      await as('admin')
        .delete(`/api/staff/${other.staffProfileId}`)
        .expect(200);
      const owner = await subject('SUPER_ADMIN');
      const refused = await as('admin')
        .delete(`/api/staff/${owner.staffProfileId}`)
        .expect(403);
      expect(refused.body.code).toBe('CANNOT_MANAGE_HIGHER_ROLE');
    });
  });

  describe('POST /api/staff/:staffProfileId/status', () => {
    it('an Admin suspends someone, who is then refused at sign-in', async () => {
      const person = await subject();
      const theirCookie = await signIn(app, person);

      const response = await as('admin')
        .post(`/api/staff/${person.staffProfileId}/status`)
        .send({ status: 'SUSPENDED' })
        .expect(200);

      expect(response.body).toMatchObject({
        staff: { status: 'SUSPENDED' },
        sessionsRevoked: 1,
        openAssignment: null,
        unsyncedWork: null,
      });
      // The session was deleted, and the account can no longer sign in at all.
      await request(app.getHttpServer())
        .get('/api/me')
        .set('Cookie', theirCookie)
        .expect(401);
      await request(app.getHttpServer())
        .post('/api/auth/sign-in/email')
        .send({ email: person.email, password: person.password })
        .expect(403);

      const back = await as('admin')
        .post(`/api/staff/${person.staffProfileId}/status`)
        .send({ status: 'ACTIVE' })
        .expect(200);
      expect(back.body).toMatchObject({
        staff: { status: 'ACTIVE' },
        sessionsRevoked: 0,
      });
    });

    it('refuses while the person is still on duty, until it is acknowledged', async () => {
      const person = await subject();
      await prisma.lineAssignment.create({
        data: {
          staffProfileId: person.staffProfileId,
          lineId,
          assignmentRole: 'JUNIOR',
          effectiveFrom: new Date('2026-01-01'),
        },
      });
      await prisma.deviceSyncReport.create({
        data: {
          staffProfileId: person.staffProfileId,
          unsentCount: 2,
          oldestUnsentAt: new Date('2026-09-17T04:00:00Z'),
          reportedAt: new Date('2026-09-18T04:00:00Z'),
        },
      });

      const refused = await as('admin')
        .post(`/api/staff/${person.staffProfileId}/status`)
        .send({ status: 'SUSPENDED' })
        .expect(422);
      expect(refused.body.code).toBe('STAFF_ON_DUTY');
      // Both reasons are named, so the Admin decides knowing each.
      expect(refused.body.details).toHaveLength(2);

      const done = await as('admin')
        .post(`/api/staff/${person.staffProfileId}/status`)
        .send({ status: 'SUSPENDED', acknowledgeOnDuty: true })
        .expect(200);
      expect(done.body.openAssignment).toMatchObject({ lineId });
      expect(done.body.unsyncedWork).toMatchObject({ unsentCount: 2 });
    });

    it('refuses your own status (422), and an Admin acting on a Super Admin (403)', async () => {
      const own = await as('admin')
        .post(`/api/staff/${staff.admin!.staffProfileId}/status`)
        .send({ status: 'SUSPENDED', acknowledgeOnDuty: true })
        .expect(422);
      expect(own.body.code).toBe('CANNOT_CHANGE_OWN_STATUS');

      const senior = await as('admin')
        .post(`/api/staff/${staff.superAdmin!.staffProfileId}/status`)
        .send({ status: 'SUSPENDED', acknowledgeOnDuty: true })
        .expect(403);
      expect(senior.body.code).toBe('CANNOT_MANAGE_HIGHER_ROLE');
    });

    it('a Senior and a Junior are refused (403)', async () => {
      const person = await subject();
      for (const who of ['senior', 'junior']) {
        const response = await as(who)
          .post(`/api/staff/${person.staffProfileId}/status`)
          .send({ status: 'SUSPENDED' })
          .expect(403);
        expect(response.body.code).toBe('PERMISSION_DENIED');
      }
    });
  });
});
